/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as EtlRouteImport } from './routes/etl'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as SettingsOrgRouteImport } from './routes/settings/org'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ModelsCreateRouteImport } from './routes/models/create'
import { Route as ModelsIdRouteImport } from './routes/models/$id'
import { Route as DataVersionsRouteImport } from './routes/data/versions'
import { Route as DataUploadRouteImport } from './routes/data/upload'
import { Route as DataProfilingRouteImport } from './routes/data/profiling'
import { Route as DataConnectorsRouteImport } from './routes/data/connectors'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemRouteImport } from './routes/admin/system'

const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const EtlRoute = EtlRouteImport.update({
  id: '/etl',
  path: '/etl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrgRoute = SettingsOrgRouteImport.update({
  id: '/settings/org',
  path: '/settings/org',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCreateRoute = ModelsCreateRouteImport.update({
  id: '/models/create',
  path: '/models/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIdRoute = ModelsIdRouteImport.update({
  id: '/models/$id',
  path: '/models/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DataVersionsRoute = DataVersionsRouteImport.update({
  id: '/data/versions',
  path: '/data/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const DataUploadRoute = DataUploadRouteImport.update({
  id: '/data/upload',
  path: '/data/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProfilingRoute = DataProfilingRouteImport.update({
  id: '/data/profiling',
  path: '/data/profiling',
  getParentRoute: () => rootRouteImport,
} as any)
const DataConnectorsRoute = DataConnectorsRouteImport.update({
  id: '/data/connectors',
  path: '/data/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/etl': typeof EtlRoute
  '/experiments': typeof ExperimentsRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scheduler': typeof SchedulerRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/data/connectors': typeof DataConnectorsRoute
  '/data/profiling': typeof DataProfilingRoute
  '/data/upload': typeof DataUploadRoute
  '/data/versions': typeof DataVersionsRoute
  '/models/$id': typeof ModelsIdRoute
  '/models/create': typeof ModelsCreateRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/org': typeof SettingsOrgRoute
  '/data/': typeof DataIndexRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/etl': typeof EtlRoute
  '/experiments': typeof ExperimentsRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scheduler': typeof SchedulerRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/data/connectors': typeof DataConnectorsRoute
  '/data/profiling': typeof DataProfilingRoute
  '/data/upload': typeof DataUploadRoute
  '/data/versions': typeof DataVersionsRoute
  '/models/$id': typeof ModelsIdRoute
  '/models/create': typeof ModelsCreateRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/org': typeof SettingsOrgRoute
  '/data': typeof DataIndexRoute
  '/models': typeof ModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/etl': typeof EtlRoute
  '/experiments': typeof ExperimentsRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scheduler': typeof SchedulerRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/data/connectors': typeof DataConnectorsRoute
  '/data/profiling': typeof DataProfilingRoute
  '/data/upload': typeof DataUploadRoute
  '/data/versions': typeof DataVersionsRoute
  '/models/$id': typeof ModelsIdRoute
  '/models/create': typeof ModelsCreateRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/org': typeof SettingsOrgRoute
  '/data/': typeof DataIndexRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/etl'
    | '/experiments'
    | '/forecasting'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/registry'
    | '/reports'
    | '/reset-password'
    | '/scheduler'
    | '/admin/system'
    | '/admin/users'
    | '/data/connectors'
    | '/data/profiling'
    | '/data/upload'
    | '/data/versions'
    | '/models/$id'
    | '/models/create'
    | '/settings/account'
    | '/settings/org'
    | '/data/'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/etl'
    | '/experiments'
    | '/forecasting'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/registry'
    | '/reports'
    | '/reset-password'
    | '/scheduler'
    | '/admin/system'
    | '/admin/users'
    | '/data/connectors'
    | '/data/profiling'
    | '/data/upload'
    | '/data/versions'
    | '/models/$id'
    | '/models/create'
    | '/settings/account'
    | '/settings/org'
    | '/data'
    | '/models'
  id:
    | '__root__'
    | '/'
    | '/etl'
    | '/experiments'
    | '/forecasting'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/registry'
    | '/reports'
    | '/reset-password'
    | '/scheduler'
    | '/admin/system'
    | '/admin/users'
    | '/data/connectors'
    | '/data/profiling'
    | '/data/upload'
    | '/data/versions'
    | '/models/$id'
    | '/models/create'
    | '/settings/account'
    | '/settings/org'
    | '/data/'
    | '/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EtlRoute: typeof EtlRoute
  ExperimentsRoute: typeof ExperimentsRoute
  ForecastingRoute: typeof ForecastingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegistryRoute: typeof RegistryRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchedulerRoute: typeof SchedulerRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DataConnectorsRoute: typeof DataConnectorsRoute
  DataProfilingRoute: typeof DataProfilingRoute
  DataUploadRoute: typeof DataUploadRoute
  DataVersionsRoute: typeof DataVersionsRoute
  ModelsIdRoute: typeof ModelsIdRoute
  ModelsCreateRoute: typeof ModelsCreateRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsOrgRoute: typeof SettingsOrgRoute
  DataIndexRoute: typeof DataIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etl': {
      id: '/etl'
      path: '/etl'
      fullPath: '/etl'
      preLoaderRoute: typeof EtlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/org': {
      id: '/settings/org'
      path: '/settings/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof SettingsOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/create': {
      id: '/models/create'
      path: '/models/create'
      fullPath: '/models/create'
      preLoaderRoute: typeof ModelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$id': {
      id: '/models/$id'
      path: '/models/$id'
      fullPath: '/models/$id'
      preLoaderRoute: typeof ModelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/versions': {
      id: '/data/versions'
      path: '/data/versions'
      fullPath: '/data/versions'
      preLoaderRoute: typeof DataVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/upload': {
      id: '/data/upload'
      path: '/data/upload'
      fullPath: '/data/upload'
      preLoaderRoute: typeof DataUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/profiling': {
      id: '/data/profiling'
      path: '/data/profiling'
      fullPath: '/data/profiling'
      preLoaderRoute: typeof DataProfilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/connectors': {
      id: '/data/connectors'
      path: '/data/connectors'
      fullPath: '/data/connectors'
      preLoaderRoute: typeof DataConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EtlRoute: EtlRoute,
  ExperimentsRoute: ExperimentsRoute,
  ForecastingRoute: ForecastingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegistryRoute: RegistryRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchedulerRoute: SchedulerRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  DataConnectorsRoute: DataConnectorsRoute,
  DataProfilingRoute: DataProfilingRoute,
  DataUploadRoute: DataUploadRoute,
  DataVersionsRoute: DataVersionsRoute,
  ModelsIdRoute: ModelsIdRoute,
  ModelsCreateRoute: ModelsCreateRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsOrgRoute: SettingsOrgRoute,
  DataIndexRoute: DataIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
